### ISSUE TITLE
Flaw with subscription management during offline mode

### ISSUE THREAD

**Issue by davenquinn** [davenquinn/Mapboard-GIS#17]
From #16 email communication with @2024andietrich:

Hi Daven:Now that you ask for suggestions - what got me frequently into trouble is the limitation to demo mode (50 moves) while MapboardGIS cannot re-establish a purchased subscription. As a field mapping geologist I happen to be frequently without internet connection and then occasionally stuck with demo mode. Being a mapper yourself you see the inconvenience.
Cheers,Andreas

It seems that there is a flaw with how the application handles network failures in demo mode.

@2024andietrich, can you confirm that you have had this issue in 4.1.0? I've rewritten the authentication system substantially during that release.

**Comment by 2024andietrich** [comment]
Hi Daven: It just happened to me working at a place with shaky internet. I am with version 4.1.0.
Cheers,Andreas


_____________Andreas Dietrich

Am Samstag, April 20, 2024, 12:24 schrieb Daven Quinn ***@***.***>:




From #16 email communication with @2024andietrich:

Hi Daven:Now that you ask for suggestions - what got me frequently into trouble is the limitation to demo mode (50 moves) while MapboardGIS cannot re-establish a purchased subscription. As a field mapping geologist I happen to be frequently without internet connection and then occasionally stuck with demo mode. Being a mapper yourself you see the inconvenience.
Cheers,Andreas

It seems that there is a flaw with how the application handles network failures in demo mode.

@2024andietrich, can you confirm that you have had this issue in 4.1.0? I've rewritten the authentication system substantially during that release.

**Comment by davenquinn** [comment]
OK, good to know. I will look into this.

**Comment by 2024andietrich** [comment]
Hi Daven:Sorry for bothering again. Got some problems with recent use of Mapboard GIS (v4.2.0). 

1) Opening some old projects repeatedly got an error messages:"Invalid value: There does not seem to be an active project""SQLite error 1: no such table: map_layer - while executing 'SELECT * FROM "map_layer" ODER BY "position"

2) Unsuccessfully tried several times to create a new project. 

2) My main concern is not being able to start a new project. Tried several times to create a project for the Chilean Andes, selecting different map areas, projection WGS84 Lon/Lat, spatialite DB. At the end of selecting the parameters always the same error message:
"File create-tables.sql does not exist"

Can you help?
Cheers,Andreas 


________________

Andreas Dietrich

**Comment by davenquinn** [comment]
Hi Andreas,

This is a major problem that has been identified by one other user. As of just a few hours ago I have fixed it locally and will push an update in the next few days.

Best,
Daven

**Comment by 2024andietrich** [comment]
Great Daven:Looking forward, just let me know.
Cheers,Andreas

________________

Andreas Dietrich



 

    Am Dienstag, 25. Juni 2024 um 11:58:25 GMT-4 hat Daven Quinn ***@***.***> Folgendes geschrieben:  
 
 

Hi Andreas,

This is a major problem that has been identified by one other user. As of just a few hours ago I have fixed it locally and will push an update in the next few days.

Best,
Daven

**Comment by davenquinn** [comment]
Hi @2024andietrich I believe that problem is resolved in version 4.2.1, which just posted to the app store. Please let me know if it didn't

**Comment by 2024andietrich** [comment]
Hi Daven:Ok great and thanks! After updating looks like working normal again.
Cheers,Andreas

_____________Andreas Dietrich

Am Donnerstag, Juni 27, 2024, 00:37 schrieb Daven Quinn ***@***.***>:




Hi @2024andietrich I believe that problem is resolved in version 4.2.1, which just posted to the app store. Please let me know if it didn't

**Comment by 2024andietrich** [comment]
Hi Daven:How can I import vector data into a Mapboard GIS project?

Sorry to bother you with such questions but I am only a simple-minded geologist without your computing skills. 

Just started a new project in Mapboard GIS with Spatialite backend. Then copied the folder to my PC, opened the project in QGIS, and added additional vector data into the Mapboard Spatialite data base. However, after re-importing it onto my iPad Mapboard does not show this data.
What is the trick?

Can you help, do you happen to have a tutorial?
Cheers,Andreas

________________

Andreas Dietrich



 

    Am Donnerstag, 27. Juni 2024 um 00:37:38 GMT-4 hat Daven Quinn ***@***.***> Folgendes geschrieben:  
 
 


Hi @2024andietrich I believe that problem is resolved in version 4.2.1, which just posted to the app store. Please let me know if it didn't

**Comment by 2024andietrich** [comment]
Hi Daven:Sorry to bother you again. Using the current version of Mapboard GIS 4.2.1.
Today the app crashed for no obvious reasons during field work. Error messages were shown only briefly, so can not tell what it said. 

After the crash opened again but without the imagery which was stored in the cash, not only for the project I just used but also for a separate project file of the same area. This is somewhat troublesome since my work area does not have cell phone and internet coverage. 

Any suggestions on how to store the imagery on a more permanent basis on my ipad?
Cheers,Andreas

________________

Andreas Dietrich
